#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.install"
exec 1> >(tee >(logger --tag=$tag))
exec 2> >(logger --stderr --priority error --tag=$tag)

modelctl set --package verbose="false"
modelctl set --package http.port="8080"
modelctl set --package http.host="127.0.0.1"
modelctl set --package webui.http.port="8081"
modelctl set --package webui.http.host="127.0.0.1"

mkdir -p "$SNAP_COMMON/usr/lib/wsl"
ln -s /var/lib/snapd/hostfs/usr/lib/wsl/lib "$SNAP_COMMON/usr/lib/wsl/lib" || true
ln -s /var/lib/snapd/hostfs/usr/lib/wsl/drivers "$SNAP_COMMON/usr/lib/wsl/drivers" || true

if snapctl is-connected hardware-observe; then
    modelctl use-engine --auto --assume-yes --verbose
elif lscpu -V &> /dev/null; then
    echo "Able to access hardware info without hardware-observe interface connection: assuming dev mode installation."
    modelctl use-engine --auto --assume-yes --verbose
else
    echo "hardware-observe interface not auto connected. Skip auto engine selection."
fi
